### ISSUE TITLE
Why base62?

### ISSUE THREAD

**Issue by garora** [robzhu/Library.WebApi#1]
Is there any specific reason for choosing [base62](https://github.com/robzhu/Library.WebApi/blob/master/DDD/Base62.cs)?

**Comment by garora** [comment]
@robzhu - are you maintaining this repository?

**Comment by robzhu** [comment]
Hey @garora, base62 doesn't need to be urlEncoded, whereas base64 has two extra characters (`/` and `+`) that make it slightly more awkward to transport across the web.
